[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Gear"
authors = [{name = "Irwin Rodríguez", email = "rodriguez.irwin@gmail.com"}]
dynamic = ["0.0.1", "Versión de la documentación"]
